### ISSUE TITLE
Text data usage ? 

### ISSUE THREAD

**Issue by Enescigdem** [dlmacedo/distinction-maximization-loss#3]
Hello,
Is this method applicable for text data ? 
I want this method for text data with using tokenizer. How can I use ?
Thanks in advance

**Comment by dlmacedo** [comment]
For text data, you use exactly the same procedure described in the README.

However, you should use DisMax loss without regularization, which is, for now, specific for image data.

The tokenization in the input layer is independent of the classification of the text that happens in the last layer.
